Documentação da Arquitetura do Projeto
VLV-subgrupo/o2t pull request #25
Opened 2024-06-06 14:49 UTC by vitorpaziam

#24 
- O diagrama em nível de componentes (C4 - Nível 3) para a arquitetura do projeto;
- Os estilos adotados na elaboração da arquitetura;
- Uma descrição textual sucinta dos principais componentes e suas responsabilidades.

2024-06-06 15:41 UTC, luiz-fll reviewed
(README.md linha 40) Na parte do MVC não precisa descrever quem é o Model, a View e o Controller?

2024-06-06 19:43 UTC, vitorpaziam commented
@luiz-fll  Melhora assim?
- **MVC (Model-View-Controller):** Este padrão divide a aplicação em três componentes principais:
    - **Model:** Representa os dados da aplicação e as regras de negócios associadas. No Spring Boot, isso é gerenciado por meio de entidades JPA que mapeiam diretamente para as tabelas do banco de dados (MySQL).
    - **View:** Refere-se ao frontend, componente independente desenvolvido em Next.js, que se comunica com o backend através de dados processados no formato JSON.
    - **Controller:** Recebe as entradas do usuário via HTTP, interage com os serviços (lógica de negócios) e retorna a resposta adequada. A nível de implementação, o Spring Boot utiliza uma divisão entre *Controllers*, que manipulam as requisições HTTP, delegando a lógica de negócios aos serviços, *Services*, que contêm a lógica de negócios da aplicação, sendo responsáveis por implementar as operações necessárias, e *Repositories*, que interagem diretamente com o banco de dados, executando operações CRUD e utilizando o Spring Data JPA para facilitar o acesso aos dados persistentes.

2024-06-06 20:08 UTC, luiz-fll commented
Sim, pode botar isso @vitorpaziam

2024-06-06 20:17 UTC, luiz-fll requested changes
Adicionar nova descrição do MVC

2024-06-06 20:30 UTC, luiz-fll approved these changes

2024-06-07 22:22 UTC, LuizGuilhermeNascimento approved these changes

2024-06-07 22:22 UTC, merged